server
{
	listen 						5000 
    listen                      5001
    listen                      5002 
    server_addr 				127.0.0.1 
	server_name 				hello.com
	root                        /Users/Charles/Desktop/42/test/zain/WS/Webserve-42
    client_max_body_size  		3m

    location /       
    {
        index 					index.html 
        http_methods  			GET  POST DELETE;
		root 					/Users/Charles/Desktop/42/test/zain/WS/Webserve-42/webpage
        upload_dir 				/Users/Charles/Desktop/42/test/zain/WS/Webserve-42/webpage/uploads
    }
} 